apiVersion: v1
kind: Service
metadata:
  name: svc-test
  namespace: argocd-test
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
